### ISSUE TITLE
Overwriting a file does not work.

### ISSUE THREAD

**Issue by merlinuwe** [mokeyish/obsidian-enhancing-export#92] opened 2023-06-26 16:31 UTC
When I try to make a .epub file, and an epub file with that name already exists, Obsidian tries endless:

![image](https://github.com/mokeyish/obsidian-enhancing-export/assets/4138869/26f3d7ad-d1e2-4201-9889-e56bed029d9e)

I have activated, to overwrite:

![image](https://github.com/mokeyish/obsidian-enhancing-export/assets/4138869/0f759f62-bfce-4f1d-bbe0-3c06dff2d6e8)

The same occures, if I make a word document:

![image](https://github.com/mokeyish/obsidian-enhancing-export/assets/4138869/e6a0875c-76b8-4ac5-949f-40e7f1dceb65)

**Comment by mokeyish** [comment] 2023-09-22 12:47
I can't reproduce your issue.

**Comment by mokeyish** [comment] 2023-09-23 02:06
Fixed by https://github.com/mokeyish/obsidian-enhancing-export/commit/dc09540958ac1d8ca715e047004728b729f1e373

**Closed** 2023-09-23 02:07 UTC
