### ISSUE TITLE
macOS: Pandoc Wikilinks Problem

### ISSUE THREAD

**Issue by blankster** [mokeyish/obsidian-enhancing-export#163] opened 2024-02-24 13:29 UTC
First of all I would like to thank you for all the work behind this plugin. Thanks to everyone involved!

I have only recently entered the macOS world and have installed Pandoc via Homebrew. The plugin seems to recognize it correctly. Unfortunately, I always get this error message, but even after some research I can't find a solution:

```
Command: pandoc -f markdown+wikilinks_title_after_pipe --resource-
path="/Users/nd/Documents/ND's Vault/Interests/Tools" --resource-
path="XX Bin/" --lua-filter="/Users/nd/Documents/ND's
Vault/.obsidian/plugins/obsidian-enhancing-export/lua/markdown.lua" -s -o
"/Users/nd/Documents/Espanso.md" -t commonmark_x-attributes
"/Users/nd/Documents/ND's Vault/Interests/Tools/Espanso.md", Error:Error:
Command failed: pandoc -f markdown+wikilinks_title_after_pipe --resource-
path="/Users/nd/Documents/ND's Vault/Interests/Tools" --resource-
path="XX Bin/" --lua-filter="/Users/nd/Documents/ND's
Vault/.obsidian/plugins/obsidian-enhancing-export/lua/markdown.lua" -s -o
"/Users/nd/Documents/Espanso.md" -t commonmark_x-attributes
"/Users/nd/Documents/ND's Vault/Interests/Tools/Espanso.md" Error at
"/Users/nd/Documents/ND's Vault/Interests/Tools/Espanso.md_chunk" (line
1, column 2): unexpected '!'
```

Screenshot of my plugin settings:
![CleanShot 2024-02-24 at 14 24 54@2x](https://github.com/mokeyish/obsidian-enhancing-export/assets/1443109/974552a8-dda3-405d-89cb-1f0adf17e366)

```
pandoc --version
pandoc 3.1.12.1
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /Users/nd/.local/share/pandoc
```

```
brew doctor
Your system is ready to brew.
```

I'm using macOS 14.3.1 (23D60) together with the latest (non beta) version of Obisidan and this plugin. I would highly appreciate help from more experienced macOS (or other) users who got it running. Please also let me know if I can provide more debug information.

Thanks in advance for any help 🙏

**Comment by mokeyish** [comment] 2024-02-24 13:35
please turn off wikilinks, this may by caused by `wikilinks_title_after_pipe` .

**Comment by blankster** [comment] 2024-02-24 13:59
> please turn off wikilinks, this may by caused by `wikilinks_title_after_pipe` .

I'm happy to do this, but how can I do this correctly? Is it an extra argument? Do I need to edit the base argument? Is it something I must set in environment variables? If this is something common, please point me in the right direction.

**Comment by FeralFlora** [comment] 2024-03-01 22:16
> I'm happy to do this, but how can I do this correctly?

Either change it in Obsidian's link settings, or by setting up a custom command template from scratch.

**Comment by aviskase** [comment] 2024-03-13 04:18
This problem was pandoc regression and it is fixed in this version https://github.com/jgm/pandoc/releases/tag/3.1.12.2 ,

**Closed** 2024-06-11 14:47 UTC
